# Generated by Django 3.2.9 on 2021-12-01 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0003_auto_20211201_1843'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='followings',
            field=models.ManyToManyField(blank=True, db_table='User_Following', related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='instruments',
            field=models.ManyToManyField(blank=True, db_table='User_Instruments', related_name='_user_customuser_instruments_+', to='band.Instrument'),
        ),
    ]
