# Generated by Django 3.2.9 on 2021-12-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(editable=False, max_length=30, unique=True, verbose_name='email address'),
        ),
    ]
