# Generated by Django 3.2.9 on 2021-12-15 02:44

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default=None, upload_to=user.models.user_profile_path),
        ),
    ]
