# Generated by Django 3.2.6 on 2021-10-29 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.IntegerField(db_column='view', default=0)),
            ],
            options={
                'db_table': 'Combination',
            },
        ),
        migrations.CreateModel(
            name='CombinationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'CombinationLog',
            },
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='cover_audio')),
                ('title', models.CharField(db_column='title', max_length=50)),
                ('category', models.CharField(db_column='category', max_length=30)),
                ('description', models.TextField(db_column='description')),
                ('views', models.IntegerField(db_column='view', default=0)),
            ],
            options={
                'db_table': 'Cover',
            },
        ),
        migrations.CreateModel(
            name='CoverTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=30)),
            ],
            options={
                'db_table': 'CoverTag',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=30)),
            ],
            options={
                'db_table': 'Instrument',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=50)),
                ('singer', models.CharField(db_column='singer', max_length=50)),
                ('category', models.CharField(db_column='category', max_length=30)),
                ('reference', models.CharField(db_column='reference', max_length=255)),
                ('description', models.TextField(db_column='description')),
            ],
            options={
                'db_table': 'Song',
            },
        ),
        migrations.CreateModel(
            name='CoverLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='band.cover')),
            ],
            options={
                'db_table': 'CoverLog',
            },
        ),
    ]
