# Generated by Django 3.2.6 on 2021-10-29 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('band', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coverlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cover',
            name='combination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='band.combination'),
        ),
        migrations.AddField(
            model_name='cover',
            name='instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='band.instrument'),
        ),
        migrations.AddField(
            model_name='cover',
            name='likes',
            field=models.ManyToManyField(db_table='Cover_Likes', related_name='like_covers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cover',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='band.song'),
        ),
        migrations.AddField(
            model_name='cover',
            name='tags',
            field=models.ManyToManyField(db_table='Cover_Tags', to='band.CoverTag'),
        ),
        migrations.AddField(
            model_name='cover',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='combinationlog',
            name='combination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.combination'),
        ),
        migrations.AddField(
            model_name='combinationlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='combination',
            name='covers',
            field=models.ManyToManyField(db_table='Cover_Combination', related_name='_band_combination_covers_+', to='band.Cover'),
        ),
        migrations.AddField(
            model_name='combination',
            name='likes',
            field=models.ManyToManyField(db_table='Combination_Likes', related_name='like_combinations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='combination',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinations', to='band.song'),
        ),
    ]
