# Generated by Django 3.2.9 on 2021-12-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0003_auto_20211201_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='description',
            field=models.TextField(blank=True, db_column='description'),
        ),
    ]
