# Generated by Django 3.2.9 on 2021-12-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0004_alter_cover_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='description',
            field=models.TextField(blank=True, db_column='description'),
        ),
    ]
