# Generated by Django 3.2.6 on 2021-12-15 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0005_alter_song_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cover',
            old_name='views',
            new_name='view',
        ),
        migrations.AddField(
            model_name='coverlog',
            name='addr',
            field=models.CharField(db_column='addr', default='', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RecoSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recos', models.CharField(db_column='recos', max_length=50)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.song')),
            ],
            options={
                'db_table': 'RecoSong',
            },
        ),
    ]
