# Generated by Django 3.2.6 on 2021-12-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0006_auto_20211215_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinationlog',
            name='addr',
            field=models.CharField(db_column='addr', default='', max_length=50),
            preserve_default=False,
        ),
    ]
